### ISSUE TITLE
Idea: Add priority for tasks similar as todo.txt

### ISSUE THREAD

**Issue by dwettstein** [todomd/todo.md#7]
The format of [todo.txt](https://todotxt.org) includes an optional priority for tasks ([todotxt_format](https://github.com/todotxt/todo.txt/blob/master/description.svg)).

As a project manager or product owner it can be very important to set a priority on tasks.

Suggestion: Add priority similar as todo.txt

Example:

```
- [ ] Feature xy
  - [ ] (A) High priority sub-task
  - [ ] (C) Low priority sub-task
- [x] (P1) Another, already done task with a different priority naming
```
